services:
  db:
    image: postgres:15
    container_name: odoo-db-erps
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data-erps:/var/lib/postgresql/data
    restart: always

  odoo:
    image: odoo:17
    container_name: odoo-app-erps
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo-data-erps:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    restart: always

volumes:
  odoo-db-data-erps:
  odoo-data-erps:
